const { readdir, createReadStream, writeFile } = require("fs-extra");
const { createInterface } = require("readline");
const { join, parse } = require("path");

// This script is not part of faast.js, but rather a tool to rewrite some parts
// of the generated docs from api-generator and api-documenter so they work with
// the website generated by docusaurus.

async function main() {
    
    const dir = "./markdown";
    const docFiles = await readdir(dir);
    const ids = [];

    for (const docFile of docFiles) {
        console.log(docFile); //fio:

        const { name: id, ext } = parse(docFile);
        if (ext !== ".md") {
            continue;
        }

        ids.push(id);

        const docPath = join(dir, docFile);
        const input = createReadStream(docPath);
        const output = [];
        const lines = createInterface({
            input,
            crlfDelay: Infinity
        });

        let title = "";
        lines.on("line", line => {
            let skip = false;
            if (!title) {
                const titleLine = line.match(/## (.*)/);
                if (titleLine) {
                    title = titleLine[1];
                }
            }
            const homeLink = line.match(/\[Home\]\(.\/index\.md\) &gt; (.*)/);
            if (homeLink) {
                // Skip the breadcrumb for the toplevel index file.
                if (id !== "faastjs") {
                    output.push(homeLink[1]);
                }
                skip = true;
            }
            // See issue #4. api-documenter expects \| to escape table
            // column delimiters, but docusaurus uses a markdown processor
            // that doesn't support this. Replace with an escape sequence
            // that renders |.
            if (line.startsWith("|")) {
                line = line.replace(/\\\|/g, "&#124;");
            }
            if (!skip) {
                output.push(line);
            }
        });

        await new Promise(resolve => lines.once("close", resolve));
        input.close();

        const header = [
            "---",
            `id: ${id}`,
            `title: ${title}`,
            `hide_title: true`,
            "---"
        ];

        console.log("Writing " + docPath); //fio:
        await writeFile(docPath, header.concat(output).join("\n"));
    }

    await writeFile(join(docPath, "ids.json"), JSON.stringify(ids, null, 4));
}

main()
    .then(() => console.log("Done"))
    .catch(err => {
        console.error(`Error processing docs.`);
        console.error(err && err.stack || err);
    });
